### ISSUE TITLE
大佬，admin下面没有index/index呀

### ISSUE THREAD

**Issue by kg-web** [KevinJay/PhalconCMS#3]
![image](https://user-images.githubusercontent.com/20922287/41085925-f31b6bf8-6a6a-11e8-9682-e65e9594d36f.png)

**Comment by aihunter666** [comment]
public/admin 是后台静态资源目录

**Comment by kg-web** [comment]
嗯嗯，后来又看了看，是通过路由会访问dashboard下面的index，可是却报了not found

![qq 20180607162803](https://user-images.githubusercontent.com/20922287/41087671-d9560002-6a6f-11e8-9b48-58096a69e703.png)

**Comment by aihunter666** [comment]
贴下nginx的error_log和app/cache/logs/目录下的日志。

**Comment by kg-web** [comment]
app/cache/logs目录下没有生成日志，下图是nginx的日志
![image](https://user-images.githubusercontent.com/20922287/41134975-c4d9d27e-6b01-11e8-8222-cded54518b32.png)

**Comment by aihunter666** [comment]
配置成域名访问试试。另外，还是关注下nginx的error_log和app/cache/logs/目录下的日志。

**Comment by kg-web** [comment]
好的，谢谢
